### ISSUE TITLE
Make it possible to serve built pages while the site is reloading

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx-autobuild#125]
Currently, when a re-build is happening, it is not possible to serve any of the already-built HTML pages from the last build. This is a pain because it can be useful to continue browsing your docs preview while a build is happening.

**Comment by asmeurer** [comment]
If not run asynchronously it would be nice if it at least queued up requests, so that if you click a link on the built site it eventually loaded it. Right now if you click a link while the build is happening nothing happens, and you have to wait for the build to happen and click the link again.

**Comment by AA-Turner** [comment]
Done in fda9582a10a80f2a68f11453449d82ec4e86bb13.

A
