### ISSUE TITLE
Provide a way to pass arbitary arguments to sphinx-build

### ISSUE THREAD

**Issue by Cadair** [sphinx-doc/sphinx-autobuild#128]
### Context

Quite often when working on the sunpy documentation I want to pass `-D plot_gallery=0` to sphinx to skip the execution of our sphinx-gallery examples. As far as I can see there is no way to do this with sphinx-autobuild at the moment?

**Comment by chrysle** [comment]
Have a look at `sphinx-autobuild`'s help:

```
...
sphinx's arguments:
  The following arguments are forwarded as-is to Sphinx. Please look at `sphinx --help` for more information.
    -b=builder, -a, -E, -d=path, -j=N, -c=path, -C, -D=setting=value, -t=tag, -A=name=value, -n, -v, -q, -Q, -w=file, -W, -T, -N, -P
```
