### ISSUE TITLE
Allow passing long forms of `sphinx-build` options to `sphinx-autobuild`

### ISSUE THREAD

**Issue by chrysle** [sphinx-doc/sphinx-autobuild#130]
### Context

Currently, it is possible to pass (most of) the **short forms** of the underlying  `sphinx-build` options to `sphinx-autobuild` .

I suppose it'd help `sphinx` users acclimate to the project if it is possible to provide the more descriptive long forms of CLI options.  

### Proposal

Add support for the long forms of the `sphinx-build` command line options.

**Comment by AA-Turner** [comment]
Done in https://pypi.org/project/sphinx-autobuild/2024.2.4/
