### ISSUE TITLE
No new release to PyPI

### ISSUE THREAD

**Issue by tsibley** [sphinx-doc/sphinx-autobuild#133]
I came here to request that `--keep-going` be added to the options passed thru to `sphinx-build`, only to see it was already added in #109 (opened two years ago, merged ~6 months ago). That's great! But there's been no new release to PyPI for over two years. Would you please consider cutting a new release for the `--keep-going` fix and other small fixes since the last release? Thanks for this very handy tooling!

**Comment by julian-poidevin** [comment]
👍🏻 Really interested as well.

**Comment by julian-poidevin** [comment]
@tsibley have you tried using the `--keep-going` option with the project latest commit ?
It is not working for me, see https://github.com/executablebooks/sphinx-autobuild/pull/109#issuecomment-1643891064

**Comment by tsibley** [comment]
Ha, no, I hadn't tried. Oy vey.

**Comment by AA-Turner** [comment]
https://pypi.org/project/sphinx-autobuild/2024.2.4/
