### ISSUE TITLE
[question] sphinx-autobuild EOS/EOL?

### ISSUE THREAD

**Issue by gen2-sys-it** [sphinx-doc/sphinx-autobuild#137]
Can we assume since no new release has made it to PyPi for almost 2.5 years, that this project is effectively EOS/EOL?

**Comment by jdillard** [comment]
I don't think it is officially EOL yet. The **executablebooks** folks have been busy working on other things and I've been trying to work with them on getting a commit bit to help with releases (but the busy part keeps getting in the way).

**Comment by pradyunsg** [comment]
No, it is not EoL.
