### ISSUE TITLE
Allow float values for the `--delay` parameter

### ISSUE THREAD

**Issue by ShaiAvr** [sphinx-doc/sphinx-autobuild#141]
### Context

I use `sphinx-autobuild` in my project, and I noticed the `--delay` parameter which controls how long to wait before opening a browser is of type `int` as can be seen from the code in [`cli.py`](https://github.com/executablebooks/sphinx-autobuild/blob/main/src/sphinx_autobuild/cli.py#L106) and in the command line:

![Screenshot 2023-11-03 104145](https://github.com/executablebooks/sphinx-autobuild/assets/35605235/037f2572-4568-4940-8782-25ded352a3cf)

This seems odd to me since time can obviously be a `float`.

The `--delay` parameter is directly passed as the parameter `open_url_delay` to the `Server.serve()` method of the `livereload` package as can be seen [here](https://github.com/executablebooks/sphinx-autobuild/blob/main/src/sphinx_autobuild/cli.py#L197). Looking at the [documentation](https://livereload.readthedocs.io/en/latest/api.html#livereload.Server.serve) of this package, it seems that this parameter doesn't have a problem with `float` values. Furthermore, looking at the [code](https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L343) of `Server.serve`, this parameter is simply passed to `time.sleep` which obviously can handle floating values.

Therefore, it is extremely easy to allow support for floating values of the `--delay` parameter. We just need to change the argument's type to `float` instead of `int` and it should work without further changes.

### Proposal

Change the type of the `--delay` argument to `float` to allow specifying floating time. It should be the only change necessary to support floating values for this parameter. I can write a PR to implement this change if there are no problems with it (Note that it would be the first time I make a PR).

**Comment by AA-Turner** [comment]
Done in f17b2ab74356e0c6dd5bb0e99079950f7062769c.

A
