### ISSUE TITLE
Proposal: move this repository to @sphinx-doc

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx-autobuild#145]
Hi @pradyunsg / @choldgraf / @GaretJax,

Would you consider moving this repo to https://github.com/sphinx-doc & having ``sphinx-autobuild`` be adopted as an "official" first-party Sphinx project?

Sorry if I've not tagged the right people -- but I think ``sphinx-autobuild`` is useful enough that we should aim to more properly integrate it into Sphinx, and have the Sphinx team help with maintenence!

Thanks,
Adam

**Comment by pradyunsg** [comment]
I'm be on-board for that! I have a partial rewrite of this project, to move it away from using `livereload` and relying natively on JS WebSockets -- and that might be a better fit for placing into Sphinx directly as well. :)

**Comment by choldgraf** [comment]
I'm in support of this as well - Executable Books has a much more narrow scope than `sphinx-autobuild` might be useful for, and the `sphinx` organization feels like a much more natural home.

For deciding on this, I suggest that we **wait until Friday the 19th** for anyone to make an objection, and if there are none, then any of the @executablebooks/steering-council members can move this repository to `sphinx-doc` (this might need coordination with @AA-Turner as well.

**Comment by gregcaporaso** [comment]
No objection from me.

**Comment by rowanc1** [comment]
I am a big fan of this being upstreamed to sphinx - thanks @AA-Turner for bringing this up! 🚀

**Comment by AA-Turner** [comment]
To move the repository I'll need to temporarily add someone with appropriate permissions here to the Sphinx organisation -- let me know who that should be!

A

**Comment by pradyunsg** [comment]
It'd likely be someone from @executablebooks/steering-council -- https://compass.executablebooks.org/en/latest/team/index.html#steering-council.

**Comment by choldgraf** [comment]
I'm happy to make the transfer if I can be useful there

**Comment by AA-Turner** [comment]
Thanks Chris! I've just sent you the invitation for @sphinx-doc.

A

**Comment by consideRatio** [comment]
@pradyunsg and @GaretJax I understand that you are the maintainers of the package on PyPI, you could provide sphinx-dev with autonomy to publish releases via github workflows in the project quite with a somewhat new PyPI feature

With a workflow like https://github.com/jupyterhub/jupyterhub-python-repo-template/blob/main/.github/workflows/release.yaml added, combined with permissions setup on PyPI as described in https://docs.pypi.org/trusted-publishers/adding-a-publisher/, repo maintainers that push a tag can trigger a release to PyPI.

**Comment by choldgraf** [comment]
### Repository moved

We only had approvals and no objections from the EB steering council, so we've decided to make this happen!

I've just moved this repository to the sphinx-doc organization. I believe that this issue is now complete! @AA-Turner you may have some follow-ups to update the CI/CD etc to follow sphinx conventions

**Comment by GaretJax** [comment]
@pradyunsg I removed myself... this project has a life on its own now and the added attack vector provided by my permissions is not warranted ;-)

/cc @consideRatio

**Comment by pradyunsg** [comment]
@AA-Turner What's your PyPI name?

**Comment by pradyunsg** [comment]
> this project has a life on its own now and the added attack vector provided by my permissions is not warranted ;-)

Thank you for all the work you've done on this project! ^>^

**Comment by AA-Turner** [comment]
It's the same (AA-Turner) - thank you!

A

**Comment by pradyunsg** [comment]
Added you as an owner, added this repository as a trusted publisher (w/ `release.yml` file and `release` environment).

<img width="420" alt="Screenshot 2024-01-27 at 18 40 08" src="https://github.com/sphinx-doc/sphinx-autobuild/assets/3275593/00d83d0e-92ee-4ecc-a0a0-23ba9b1106a1">

**Comment by pradyunsg** [comment]
Closing this out since the move has completed. If there's anything else needed here, @AA-Turner we have lots of common spaces and you know how to reach me! :)

**Comment by AA-Turner** [comment]
@GaretJax do you want to keep commit permissions? I've currently kept you and Pradyun -- happy to add back anyone else from Executable Books if they'd like to keep permissions.

A

**Comment by GaretJax** [comment]
@AA-Turner I'm fine without, thank you for asking!
