### ISSUE TITLE
Theme error: no theme named 'pydata_sphinx_theme'

### ISSUE THREAD

**Issue by shapiromatron** [sphinx-doc/sphinx-autobuild#149]
I get an error in configuration when running `sphinx-autobuild`, but it works just fine when using the standard `sphinx-build`.

I'm using the [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme). 

```bash
► sphinx-build -b html source build/html
... build succeeded.

► sphinx-autobuild -b html source build/html
sphinx_args.filenames=[]
[sphinx-autobuild] > sphinx-build -b html source build/html
Running Sphinx v7.2.6
loading pickled environment... done

Theme error:
no theme named 'pydata_sphinx_theme' found (missing theme.conf?)
Sphinx exited with exit code: 2
The server will continue serving the build folder, but the contents being served are no longer in sync with the documentation sources. Please fix the cause of the error above or press Ctrl+C to stop the server.
[I 240307 16:58:07 server:335] Serving on http://127.0.0.1:8000
[I 240307 16:58:07 handlers:62] Start watching changes
[I 240307 16:58:07 handlers:64] Start detecting changes
^C[I 240307 17:00:09 server:358] Shutting down..
```

The rendered output looks fine with the standard build command, I'm not sure what the issue is. Any ideas?

**Comment by pradyunsg** [comment]
Hmm, sphinx-autobuild literally just calls sphinx-build under the hood. Could you run things in verbose mode and, possibly, also print sys.path from conf.py to gather more diagnostics on this.

**Comment by pradyunsg** [comment]
Also, are both Sphinx and sphinx-autobuild installed in the same directory?
