### ISSUE TITLE
Why did this project move away from the src/ layout?

### ISSUE THREAD

**Issue by pradyunsg** [sphinx-doc/sphinx-autobuild#159]
Coming from 359f3e6 -- I almost wrote a comment there but figured doing this over an issue has better odds of discoverability in the future. :)

@AA-Turner Is there a specific reason this project moved away from using an src/ layout?

This current setup makes it trickier to test things, since I'm having local changes interfere when trying to use an installed copy from an existing release (see point 2 in https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/).

**Comment by AA-Turner** [comment]
To match the general style of the other ``Sphinx*`` projects, in the main. I admit I tend to use editable installs by default and don't have any issues.

I don't have strong opinions, really, but regardless we should add something to the contributor guide to document what works best.

A
