### ISSUE TITLE
confusion of required arguments

### ISSUE THREAD

**Issue by Borda** [sphinx-doc/sphinx-autobuild#162]
Hello, I would love to try this extension in https://github.com/Lightning-AI/torchmetrics/pull/2518, but so far hitting some issues; the latest one with installing from master (lat release does not work with py3.9, https://github.com/sphinx-doc/sphinx-autobuild/issues/155#issuecomment-2112022210)

Following the example in the readme, https://github.com/sphinx-doc/sphinx-autobuild#using-with-makefile, I get the following error:
```
make[1]: Entering directory '/home/jirka/Workingspace/pt-metrics/docs'
sphinx-autobuild "source" "build" -W 
usage: sphinx-autobuild [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-autobuild: error: the following arguments are required: sourcedir, outputdir, filenames
make[1]: *** [Makefile:22: livehtml] Error 2
```
Based on the `usage: sphinx-autobuild [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]` filenames are optional, but in fact, they are required or what am I missing?

**Comment by pradyunsg** [comment]
> sphinx-autobuild "source" "build" -W

Does `sphinx-autobuild -W "source" "build"` work? (asking based on the help error's message, which indicates options need to before the positional arguments.

**Comment by Borda** [comment]
> Does `sphinx-autobuild -W "source" "build"` work?

not really, getting this error:
```
metrics/docs$ sphinx-autobuild -W "source" "build"
usage: sphinx-autobuild [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-autobuild: error: the following arguments are required: sourcedir, outputdir, filenames
```

**Comment by return42** [comment]
Should be closed by https://github.com/sphinx-doc/sphinx-autobuild/pull/164
