### ISSUE TITLE
WebSocket hot reload doesn’t work with host 0.0.0.0

### ISSUE THREAD

**Issue by holesch** [sphinx-doc/sphinx-autobuild#165]
When using `--host 0.0.0.0` to bind to all network interfaces, then hot reload doesn't work anymore. I can see this error in the browser:
```
Firefox can’t establish a connection to the server at ws://0.0.0.0:8000/websocket-reload.
```

This broke with version 2024.04.13. I'm guessing with commit 3a32d1b ("Implement hot reloading with websockets").

**Comment by AA-Turner** [comment]
PR welcome, but otherwise I would just suggest using localhost.

A
