### ISSUE TITLE
run in background ?

### ISSUE THREAD

**Issue by mireille-raad** [sphinx-doc/sphinx-autobuild#62]
Is there an option to run sphinx-autobuild in background? the same way that you would do with -d parameter in docker?

**Comment by ngzhian** [comment]
You can probably use your shell's background option, e.g. in bash: `sphinx-autobuild <options> &`

**Comment by pradyunsg** [comment]
Sounds like a reasonable request. We can probably do a `--detach` flag for this.

**Comment by TrueOsiris** [comment]
Hi. Did this ever get implemented?

**Comment by pradyunsg** [comment]
No.

**Comment by AA-Turner** [comment]
PR welcome, but otherwise I recommend using your shell's features for this.

A
