### ISSUE TITLE
Support newly documented (but previously available) -M option

### ISSUE THREAD

**Issue by nwwells** [sphinx-doc/sphinx-autobuild#64]
See https://github.com/sphinx-doc/sphinx/pull/3938/files for the documentation, and https://github.com/sphinx-doc/sphinx/blob/master/sphinx/make_mode.py for implementation

Basically `-M` is a alias for `-b` with some additional handling for other features like a `help` and LaTeX.

Assuming this is just something we can pass through, it would allow me to do something like

```
make html --auto
```

and simply use sphinx-autobuild as the `SPHINXBUILD` option.

**Comment by rowanG077** [comment]
I have implemented this feature: https://github.com/rowanG077/sphinx-multibuild

**Comment by pradyunsg** [comment]
Looks like a reasonable request!

**Comment by deliciouslytyped** [comment]
Tangentially related https://github.com/sphinx-doc/sphinx/issues/12631 , should also show up in --help eventually.

**Comment by deliciouslytyped** [comment]
xref https://github.com/sphinx-doc/sphinx-autobuild/pull/151

**Comment by AA-Turner** [comment]
Closed in #173.

A
