### ISSUE TITLE
Allow for generic build command (for use with jupyter-book)

### ISSUE THREAD

**Issue by amichuda** [sphinx-doc/sphinx-autobuild#99]
I wanted to see if it was possible to use `sphinx-autobuild` with building with `jupyter-book`. As of now it seems that this is possible as the `get_builder` function runs `sphinx` explicitly. Would it be possible to have the server watch a `sourcedir` and `outdir` but for a generic command (such as `jb build`)?

**Comment by pradyunsg** [comment]
You can add `--pre-build "jb build"` today, to run that build and pass additional `--watch` options as well.

As it stands, this is a really thin wrapper over `livereload` (the Python package). It might make sense for jupyter-book to get a `serve` command that uses it. FWIW, it's even pretty straightforward to write a script that does the right thing, using only `livereload`.

```py
import subprocess
import livereload

def run():
    subprocess.run(["jupyter-book", "build"])

server = livereload.Server()
server.watch('docs/source', run)

server.serve(root='docs/build/html')
```

**Comment by ashwin153** [comment]
I want to use sphinx-autorebuild with sphinx-multiversion, which itself wraps the sphinx-build command to build versioned documentation. Would it be possible to parameterize the currently hard-coded `sphinx-build` invocation via a command line option (e.g., `--build-cmd`)?

**Comment by chrisjsewell** [comment]
Heya, as I note in https://github.com/executablebooks/jupyter-book/issues/1455:

jupyter-book now has the ability for external packages to "inject" commands in to its CLI, this is for example how `jupyter-book toc` works (executablebooks/sphinx-external-toc@ec4a439/setup.cfg#L43-L44). By the same mechanism, sphinx-autobuild could inject a `jupyter-book serve` command, that is customized for jupyter-book
